version: '3.8'

services:
  sqlserver-procedimientos:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-procedimientos
    environment:
      SA_PASSWORD: "SimplePass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

  sqlserver-init:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-init
    environment:
      SA_PASSWORD: "SimplePass123"
      ACCEPT_EULA: "Y"
    depends_on:
      - sqlserver-procedimientos
    entrypoint: /bin/bash
    command: -c "sleep 50 && /opt/mssql-tools18/bin/sqlcmd -S sqlserver-procedimientos -U sa -P SimplePass123 -d master -i /docker-entrypoint-initdb.d/init.sql -C && echo 'Script ejecutado exitosamente' && sleep infinity"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  procedimientosrp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procedimientosrp
    environment:
      SPRING_APPLICATION_NAME: "procedimientosrp"
      SPRING_DATASOURCE_PROCEDIMIENTOSRP_JDBC_URL: "jdbc:sqlserver://sqlserver-procedimientos:1433;databaseName=PROCEDIMIENTOS;encrypt=false;trustServerCertificate=true"
      SPRING_DATASOURCE_PROCEDIMIENTOSRP_USERNAME: "sa"
      SPRING_DATASOURCE_PROCEDIMIENTOSRP_PASSWORD: "SimplePass123"
      SPRING_DATASOURCE_PROCEDIMIENTOSRP_DRIVER_CLASS_NAME: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.SQLServerDialect"
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "20"
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "30000"
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "2000000"
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "30000"
      SPRING_DATASOURCE_HIKARI_POOL_NAME: "HikariPoolOrcl"
    ports:
      - "8089:8080"
    depends_on:
      - sqlserver-procedimientos
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:192.168.2.12"

  frontend:
    image: plantilla-login:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge
